// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: api/scrap.proto

package scrap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScrapClient is the client API for Scrap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrapClient interface {
	GetTopWords(ctx context.Context, in *GetTopWordsReq, opts ...grpc.CallOption) (*GetTopWordsRes, error)
}

type scrapClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapClient(cc grpc.ClientConnInterface) ScrapClient {
	return &scrapClient{cc}
}

func (c *scrapClient) GetTopWords(ctx context.Context, in *GetTopWordsReq, opts ...grpc.CallOption) (*GetTopWordsRes, error) {
	out := new(GetTopWordsRes)
	err := c.cc.Invoke(ctx, "/Scrap/GetTopWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrapServer is the server API for Scrap service.
// All server must embed UnimplementedScrapServer
// for forward compatibility
type ScrapServer interface {
	GetTopWords(context.Context, *GetTopWordsReq) (*GetTopWordsRes, error)
	mustEmbedUnimplementedScrapServer()
}

// UnimplementedScrapServer must be embedded to have forward compatible server.
type UnimplementedScrapServer struct {
}

func (UnimplementedScrapServer) GetTopWords(context.Context, *GetTopWordsReq) (*GetTopWordsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopWords not implemented")
}
func (UnimplementedScrapServer) mustEmbedUnimplementedScrapServer() {}

// UnsafeScrapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrapServer will
// result in compilation errors.
type UnsafeScrapServer interface {
	mustEmbedUnimplementedScrapServer()
}

func RegisterScrapServer(s grpc.ServiceRegistrar, srv ScrapServer) {
	s.RegisterService(&Scrap_ServiceDesc, srv)
}

func _Scrap_GetTopWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopWordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapServer).GetTopWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Scrap/GetTopWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapServer).GetTopWords(ctx, req.(*GetTopWordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Scrap_ServiceDesc is the grpc.ServiceDesc for Scrap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scrap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Scrap",
	HandlerType: (*ScrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopWords",
			Handler:    _Scrap_GetTopWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/scrap.proto",
}
